default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  host: localhost
  username: agungyuliaji
  password: simon
  pool: 5

development:
  <<: *default
  database: testproject_development

test:
  <<: *default
  database: testproject_test

production:
  <<: *default
  database: testproject_production
  username: testproject
  password: <%= ENV['TESTPROJECT_DATABASE_PASSWORD'] %>
